model_name = "sentence-transformers/sentence-t5-base"
output_name = "t5-base"
cache_dir = "./cache/pairwise_dimension_reduction_beir/t5-base"
output_path = "./outputs/pairwise_dimension_reduction_beir/results/t5-base.json"
attribution_path = "./output_dim_eval/t5-base__beir.json"
