model_name = "intfloat/e5-large-v2"
output_name = "e5-large-v2"
cache_dir = "./cache/pairwise_dimension_reduction_mteb/e5-large-v2"
result_output_dir = "./outputs/pairwise_dimension_reduction_mteb/"
output_path = "./outputs/pairwise_dimension_reduction_mteb/results/e5-large-v2.json"
attribution_path = "./output_dim_eval/e5-large-v2__mteb.json"
